services:
  fleet:
    image: r1-sim:jazzy
    container_name: gazebo_sim
    network_mode: host
    ipc: host
    environment:
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
    command: ["headless"]
  gui:
    image: r1-sim:jazzy
    network_mode: host
    ipc: host
    command: ["gui"]
    environment:
      DISPLAY: ${DISPLAY}
      LIBGL_ALWAYS_SOFTWARE: "1"
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
      QT_X11_NO_MITSHM: "1"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
