solve_ik_poses:
  target_link: "left_gripper_link"
  gripper_standoff: 0.2

  shelves:
    A:
      orientation: {x: 0.0, y: -0.66262, z: 0.0, w: 0.7489557}
      positions:
        - {x: 0.6, y: 0.1, z: 0.25}
        - {x: 0.6, y: 0.2, z: 0.25}
        - {x: 0.6, y: 0.3, z: 0.25}
        - {x: 0.6, y: 0.35, z: 0.25}
        - {x: 0.6, y: 0.4, z: 0.25}
        - {x: 0.6, y: 0.45, z: 0.25}

    B:
      orientation: {x: 0.0, y: -0.7071, z: 0.0, w: 0.7071}
      positions:
        - {x: 0.6, y: 0.1, z: 0.69}
        - {x: 0.6, y: 0.2, z: 0.69}
        - {x: 0.6, y: 0.3, z: 0.69}
        - {x: 0.6, y: 0.4, z: 0.69}
        - {x: 0.6, y: 0.5, z: 0.69}

    C:
      orientation: {x: 0.0, y: -0.7071, z: 0.0, w: 0.7071}
      positions:
        - {x: 0.6, y: 0.1, z: 1.13}
        - {x: 0.6, y: 0.2, z: 1.13}
        - {x: 0.6, y: 0.3, z: 1.13}
        - {x: 0.6, y: 0.4, z: 1.13}
        - {x: 0.6, y: 0.5, z: 1.13}
